name: Replace Variables in File
description: This workflow replaces variables in a file using a bash script.
inputs:
  github_vars:
    description: 'The JSON with the variables to replace in the file.'
    required: true
  file_path:
    description: 'The path of the file to be updated.'
    required: true
  prefix:
    description: 'The prefix used for each variable in the file.'
    required: true
  suffix:
    description: 'The suffix used for each variable in the file.'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  #entrypoint: 'entrypoint.sh'
  args:
   # - './script_name.sh'
    - '${{inputs.github_vars}}'
    - '${{inputs.file_path}}'
    - '${{inputs.prefix}}'
    - '${{inputs.suffix}}'
